feat: game header and notes
matteocodogno/CipherQuest pull request #94
Opened 2024-12-20 15:40 UTC by CimsW3llD

Show **Mission rules** button & dialog
Show **logout** button & dialog
Show **notes** button & dialog

closes #53 #36

2024-12-20 16:05 UTC, IgnacioUtrilla requested changes
**TODO:** Il logout non riporta alla login page.

2024-12-20 16:10 UTC, IgnacioUtrilla requested changes

2024-12-20 16:10 UTC, IgnacioUtrilla commented on frontend/src/components/chat/dialog/rules-dialog.tsx
> +          {AccordionMenu.map((item) => (
```suggestion
          {accordionMenu.map((item) => (
```

2024-12-20 16:10 UTC, IgnacioUtrilla commented on frontend/src/components/chat/dialog/rules-dialog.tsx
I fragment possono anche essere rimossi

2024-12-29 22:35 UTC, matteocodogno submitted a review, later dismissed

2024-12-29 22:38 UTC, merged